import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [cat, setCat] = useState({});
  // we start with no cat
  // then we fetch one, now we need save it!
  // then we display the cat

  async function fetchCat() {
    const response = await fetch("https://cataas.com/cat?json=true");
    const data = await response.json();
    console.log("SUCCES?", data);
    setCat(data);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {cat.url ? <img src={`https://cataas.com${cat.url}`} /> : "Loading"}
        <button onClick={fetchCat}>Fetch a cat!</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
